name: deploy-selfhosted
on: { push: { branches: [ main ] } }

jobs:
  build-and-deploy:
    runs-on: self-hosted
    defaults: { run: { shell: bash } }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # --------- ส่วน frontend  ---------

      - name: Build frontend
        working-directory: frontend
        run: |
          set -euxo pipefail
          echo "VITE_API_BASE_URL=http://127.0.0.1:8080" > .env.production
          npm ci
          npm run build
          test -f dist/index.html
          chmod -R u+rwX,go+rX dist

      - name: Deploy frontend
        run: |
          set -euxo pipefail
          # ลบของเก่าให้เหมือน --delete
          rm -rf /var/www/hospital/frontend/*
          # คัดลอกจาก dist แบบรักษาโครง/สิทธิ์
          tar -C frontend/dist -cf - . | tar -C /var/www/hospital/frontend -xf -
          # กันสิทธิ์อ่าน
          find /var/www/hospital/frontend -type d -exec chmod 755 {} +
          find /var/www/hospital/frontend -type f -exec chmod 644 {} +

      # --------- ส่วน backend  ---------
      - name: Prepare backend release dir
        id: prep
        run: |
          set -euxo pipefail
          TS=$(date +%s); REL="/var/www/hospital/releases/backend-${TS}"
          mkdir -p "$REL"; echo "REL=$REL" >>"$GITHUB_OUTPUT"

      - name: Copy backend source to release
        run: |
          set -euxo pipefail
          rsync -az --delete --exclude .git --exclude vendor --exclude node_modules \
            backend/ "${{ steps.prep.outputs.REL }}/"

      - name: Link shared storage/cache and .env
        run: |
          set -euxo pipefail
          cd "${{ steps.prep.outputs.REL }}"
          cp /var/www/hospital/shared/.env .env
          rm -rf storage bootstrap/cache
          ln -s /var/www/hospital/shared/storage storage
          ln -s /var/www/hospital/shared/bootstrap/cache bootstrap/cache
          if grep -q '^DB_CONNECTION=sqlite' .env; then
            DB_PATH="$(grep '^DB_DATABASE=' .env | cut -d= -f2-)"
            [ -n "$DB_PATH" ] && touch "$DB_PATH"
          fi

      - name: Composer install (prod) + migrate + caches
        run: |
          set -euxo pipefail
          cd "${{ steps.prep.outputs.REL }}"
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          php artisan key:generate --force || true
          php artisan migrate --force
          php artisan config:cache && php artisan route:cache && php artisan view:cache

      - name: Switch current backend symlink & reload nginx
        run: |
          set -euxo pipefail
          ln -sfn "${{ steps.prep.outputs.REL }}" /var/www/hospital/backend
          chown -hR deploy:deploy /var/www/hospital
          (sudo restorecon -Rv /var/www/hospital || true)
          sudo systemctl reload nginx || true
